### ISSUE TITLE
Get lots of warnings when including pyopencl-complex.h

### ISSUE THREAD

**Issue by abrahamneben** [inducer/pyopencl#134]
When including pyopencl-complex.h, I get a large number of compiler notes and warnings which always hide my actual errors. Does this happen to everyone, or am I doing something wrong?

[warnings.txt](https://github.com/pyopencl/pyopencl/files/403131/warnings.txt)

**Comment by inducer** [comment]
I've seen these messages (on Apple--which is where you're running, correct?). I haven't seen them occur on any other implementation, and I don't even understand what the compiler is talking about--otherwise I'd be happy to try and work around them. If you find a viable workaround, let me know. I'd be happy to include it.

**Comment by inducer** [comment]
Also, it might be a good idea to poke the list about this--thus far, I'm the only one who got notified about this report.

**Comment by abrahamneben** [comment]
I'm on Mac OS X 10.11.6 with an Intel HD Graphics 5000 1536 MB graphics card. I'll post to the list.

**Comment by maweigert** [comment]
Hey, 
I get the same warning when including `pyopencl-complex.h` on Mac OSX 10.11.6, GeForce GT 750M (but not on any Linux machine). The specific warnings are all related to the definitions of functions like
```c
//pyopencl-complex.h:35
REAL_TP TPROOT##_real(TP a) { return a.real; } 
```
since after inlining them 
```c
//pyopencl-complex.h:35
inline REAL_TP TPROOT##_real(TP a) { return a.real; } 
```
all of the gazillions warning go away.

@inducer Are there any specific disadvantages of that? I'd be happy seeing those warnings vanish as that would make the now chatty compiler output sensible again :)

If there are not immediate objections to the inlining, I could submit a (simple) patch.

**Comment by inducer** [comment]
It doesn't seem as though `inline` functions are explicitly disallowed in CL. Thanks for offering to submit a patch. Please post it here:

https://gitlab.tiker.net/inducer/pyopencl

as a merge request. You should have received an email with account info.
