### ISSUE TITLE
Invalid source error on openSUSE Tumbleweed for Clover

### ISSUE THREAD

**Issue by Talkless** [inducer/pyopencl#230]
Hi,

Firs of all sorry if I'm bothering with "too old version", but on openSUSE Tumbleweed with `python-pyopencl` 2016.2-11.29 package from [home:syeg](https://build.opensuse.org/package/show/home:syeg/python-pyopencl) repository I get this kind of output while running `/usr/share/doc/packages/python-pyopencl/examples/demo.py`:
```
Choose platform:
[0] <pyopencl.Platform 'Clover' at 0x7fb8f26b7ea0>
[1] <pyopencl.Platform 'Portable Computing Language' at 0x7fb8ebd7a598>
Choice [0]:
Set the environment variable PYOPENCL_CTX='' to avoid being asked again.
Traceback (most recent call last):
  File "/usr/share/doc/packages/python-pyopencl/examples/demo.py", line 25, in <module>
    """).build()
  File "/usr/lib64/python2.7/site-packages/pyopencl/__init__.py", line 438, in build
    options_bytes=options_bytes, source=self._source)
  File "/usr/lib64/python2.7/site-packages/pyopencl/__init__.py", line 473, in _build_and_catch_errors
    raise err
pyopencl.cffi_cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - 

Build on <pyopencl.Device 'NV117' on 'Clover' at 0x559db5474e28>:

invalid source
(options: -I /usr/lib64/python2.7/site-packages/pyopencl/cl)
(source saved as /tmp/tmpxx1mk5.cl)
```

source `/tmp/tmpxx1mk5.cl`:
```

__kernel void sum(
    __global const float *a_g, __global const float *b_g, __global float *res_g)
{
  int gid = get_global_id(0);
  res_g[gid] = a_g[gid] + b_g[gid];
}
```

My hardware: laptop with `i7-4710HQ` and `NVIDIA Corporation GM107M [GeForce GTX 860M] (rev a2)`, with `nouveau`.

Should I ask repository maintainer to update pyopencl? Would that help?

Thanks!

**Comment by inducer** [comment]
I don't think this is something PyOpenCL can do much about. Your OpenCL implementation (Clover+nouveau) is being handed valid OpenCL C source and is claiming it's invalid. That's non-compliant behavior. To put that in context, nobody is claiming that compute with Clover+nouveau is mature or ready for production use--so you use experimental software, and you get what you get.

Some things to try:

- It may be that nouveau+clover want to be handed SPIR-V rather than OpenCL C (I think I read a related news article recently). That's the direction in which OpenCL is headed anyway, and so if I was implementing OpenCL, I would start with that, too. You could try the related PyOpenCL test. (Though I'm not sure that support was in PyOpenCL 2016.x.)

- See if you can get a C-based OpenCL "hello world" program to execute successfully. If you can, then come back to this issue. If that's the case, there may be an issue with PyOpenCL after all.

Lastly, this being a tech support matter, it would be great if you could direct further discussion of this to the mailing list.

**Comment by Talkless** [comment]
Yeah I guess it's more like a support question, I agree.
What mailing list do you have in mind? PyOpenCL, OpenCL, Mesa..?

**Comment by inducer** [comment]
If you agree that this sounds more like an issue with the OpenCL implementation, I imagine they (Mesa likely) might be the better people to talk to. But I imagine the folks on the PyOpenCL list (me certainly included) would like to hear what you find regarding the viability of the Clover stack for practical use.

**Comment by Talkless** [comment]
I've got informed on dri-devel channel that it's not expected to work, and I should try again in autumn:

>[20:43] <imirkin_> Talkless: clover + amd is actually semi-ok
>[20:43] <imirkin_> but with nouveau, it just doesn't work at all right now (upstream)
>[20:44] <imirkin_> people are working on bringing opencl c -> something nouveau understands into mesa
>[20:44] <robclark> basically, for nouveau, check back in Sept or so (since it depends on among other things, llvm7 which won't be released until then)
>[20:44] <imirkin_> but that's still some time away from being merged in
I should wait for

**Comment by inducer** [comment]
Thanks for sharing that update!
