### ISSUE TITLE
enqueue_copy_buffer disapeared ?

### ISSUE THREAD

**Issue by kif** [inducer/pyopencl#248]
Hi Andreas,

I tested our code on the master version of pyopencl to ensure the forthcoming release is future-proof.

Apparently, *pyopencl.enqueue_copy_buffer* disappeared ? but it is still documented. Is this a foreseen move (replaced by *enqueue_copy* ?) or is it a regression in pyopencl ?

Cheers

Jerome

**Comment by inducer** [comment]
That family of functions has been [deprecated since 2011](https://github.com/inducer/pyopencl/blob/7c2f3ba43337b98e57db06d2e7b82de3e07266ae/pyopencl/__init__.py#L681-L711) and complained with `DeprecationWarnings` when used. (Python helpfully doesn't show those by default, although that may have changed recently.) I finally bit the bullet and removed them in favor of plain `enqueue_copy` with the pybind11 restructuring.

**Comment by inducer** [comment]
In c5433a3, I have also removed the extraneous documentation.
