### ISSUE TITLE
bool type in kernel mapped to which Python type?

### ISSUE THREAD

**Issue by yxliang01** [inducer/pyopencl#304]
Looks like in OpenCL C, `bool` is a valid type. However, in the PyOpenCL doc, it doesn't mention which Python type it's mapped to.

**Comment by inducer** [comment]
That's intentional, because OpenCL C does not specify a bit size (or binary representation) of the bool data type. If you look at the CL header, it says even there:
```c
typedef cl_uint             cl_bool;                     /* WARNING!  Unlike cl_ types in cl_platform.h, cl_bool is not guaranteed to be the same size as the bool in kernels. */
```
So I figured it would be safer to not define a host mapping for `bool`. Although I wouldn't recommend it, you can always register one yourself.

**Comment by yxliang01** [comment]
@inducer  Right, I have realized this in PyOpenCL library. To be honest, I feel they should have mentioned how to deal with this in their documentations though. So, I feel it might also be good if this is mentioned in the documentation for PyOpenCL? It has only mentioned that boolean array is stored as `np.int8`, but didn't say about `bool` itself.

**Comment by inducer** [comment]
Thanks for the suggestion. Just pushed an update. Docs should update themselves in a bit.
