### ISSUE TITLE
New Pip Version 2020.3 Fails 

### ISSUE THREAD

**Issue by big-c-note** [inducer/pyopencl#404]
Tests started failing for `pip install pyopencl` with the following error for new version `pyopencl==2020.3`. I tried locally as well with the same error. Let me know if you need more info.

I'm on Linux, Ubuntu 20.04

Using `pip3 install pyopencl==2020.2.2` continues to work.

```
       70 | #include <CL/cl.h>
          |          ^~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by inducer** [comment]
I think what you mean here is that there are binaries for PyOpenCL 2020.2.2 on the package index, but not for 2020.3.

**Comment by inducer** [comment]
Pushed v2020.3.1, triggered Wheel builds: https://travis-ci.org/github/inducer/pyopencl/builds/744802850. We'll see if that helps.

https://pypi.org/project/pyopencl/2020.3.1/#files

**Comment by isuruf** [comment]
Nope. `Build type disabled via repository settings (push).`

**Comment by inducer** [comment]
Well, there was actually more going on:

- A Travis build failed a while ago in a PR, and I got annoyed. I saw that Travis was enabled for branch pushes and thought "that makes no sense, it's only for tags/releases", and disabled it.
- 2020.3 wouldn't have built anyway because I didn't push the commit with the tag, I pushed the one after that.
- I then pushed 2020.3.1, and nothing built.
- Realizing my mistake, I reenabled branch push builds and manually triggered the build I linked above.

**Comment by isuruf** [comment]
There's one issue though. You can't manually trigger a tag build. (the one linked above is a build for a commit) Only tag builds upload to PyPI. Only way to fix this would be to delete the tag in github and re push the tag.

**Comment by inducer** [comment]
Good idea, thanks! https://travis-ci.org/github/inducer/pyopencl/builds/744805910

**Comment by inducer** [comment]
There are binary wheels now. Let me know if you continue to have trouble.

**Comment by big-c-note** [comment]
Tests work everywhere, thanks.
