### ISSUE TITLE
Unsafe use of fill_uniform in test_array.py

### ISSUE THREAD

**Issue by aarongreig** [inducer/pyopencl#413]
Forgive me if I'm misunderstanding something, but I think [this](https://github.com/inducer/pyopencl/blob/master/test/test_array.py#L745) use of `fill_uniform` immediately preceded by a `.get()` call on the array can result in a data race, since `fill_uniform` invokes the `__call__` operator of `kernel` and returns the event without waiting for it.

**Comment by inducer** [comment]
Thanks for the report. As I see it, this is actually OK, since the event returned by `.get` gets added to `Array.events`, which gets passed to `wait_for` for the fill kernel. Nonetheless, you're poking an area that currently is kind of wonky, as PyOpenCL's array type doesn't handle dependencies quite as well as it should. See #303 for further discussion. Feel free to chime in there, and feel free to comment/reopen this if you disagree.

**Comment by aarongreig** [comment]
Ah sorry not preceded by, *succeeded* by. What I meant is the `fill_uniform` event is not waited on by the `.get()` that comes after it to check the results, I'm still reading so I'm not sure yet but is there a mechanism that adds the event generated by a kernel invocation to the array objects that were passed to it as arguments?

**Comment by inducer** [comment]
> is there a mechanism that adds the event generated by a kernel invocation to the array objects that were passed to it as arguments?

Not automatically, no. How do you feel about #414?
