### ISSUE TITLE
source tarball contains binary artefact _skbuild/linux-x86_64-3.11/cmake-install/pyopencl/_cl.cpython-311-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by anbe42** [inducer/pyopencl#670]
The 2022.3 source tarball <https://files.pythonhosted.org/packages/c2/f5/cce0353053ab9438145daf0a653878742259b158aea1234d0336e69da4e9/pyopencl-2022.3.tar.gz> contains a prebuilt binary artefact `_skbuild/linux-x86_64-3.11/cmake-install/pyopencl/_cl.cpython-311-x86_64-linux-gnu.so`.

**Comment by inducer** [comment]
Thanks for letting me know! This got included by accident after being created during work on #546. I've fixed `MANIFEST.in` so that these files are no longer included and released 2022.3.1 (Ci will upload to pypi after wheel build completes).

As it is, I am not inclined to yank the affected releases.
